@echo off
CHCP 65001
CLS
SETLOCAL enabledelayedexpansion

color 0a
title UNKNOWN TERMINAL (PORT 23)

ECHO A ^ B
SET /P A="A: "
SET /P B="B: "

SET /A RES=1

FOR /L %%I IN (1,1,%B%) DO (
    SET /a RES=!RES! * %A%
)

ECHO RESULT: !RES!
PAUSE

ECHO ACCESSING NSA DATABASE...
TIMEOUT /t 2 > NUL
ECHO BYPASSING FIREWALL...
TIMEOUT /t 2 > NUL

FOR /l %%I IN (1,1,5) DO (
    CLS
    ECHO DOXING YOUR IP...
    TIMEOUT /t 1 > NUL
)

ECHO.
ECHO UH OH, WE GOT UR IP MATE!
PAUSE

IPCONFIG
PAUSE

cls
timeout /t 1 > nul
ECHO hold 
timeout /t 1 > nul
ECHO me
timeout /t 1 > nul
ECHO close
timeout /t 1 > nul
ECHO look me dead in my eyes
timeout /t 2 > nul
cls

ECHO dead
timeout /t 1 > nul
ECHO in
timeout /t 1 > nul
ECHO my
timeout /t 1 > nul
ECHO 'til the day that i die
timeout /t 2 > nul
cls

ECHO dead
timeout /t 1 > nul
ECHO in-
timeout /t 1 > nul
ECHO -side
timeout /t 1 > nul
ECHO I just wanna feel alive
timeout /t 2 > nul
cls

ECHO with you
ECHO i'm alive
timeout /t 1 > nul
ECHO with you i'm alive
timeout /t 2 > nul
cls

ECHO fall in love
timeout /t 1 > nul
ECHO but it left me lonely
timeout /t 2 > nul
cls

ECHO try to trust
timeout /t 1 > nul
ECHO but it burn me slowly
timeout /t 3 > nul
cls

echo i didnt know
timeout /t 1 > nul
echo what I was looking for
timeout /t 2 > nul
cls

echo 'Til
timeout /t 1 > nul
echo I
timeout /t 1 > nul
echo Found
timeout /t 1 > nul
echo	 ,ggg,        gg    ,ggggggg,  ,ggggggggggg,   
echo	dP""Y8b       88  ,dP""""""Y8bdP"""88""""""Y8, 
echo	Yb, `88       88  d8'    a  Y8Yb,  88      `8b 
echo	 `"  88       88  88     "Y8P' `"  88      ,8P 
echo	     88aaaaaaa88  `8baaaa          88aaaad8P"  
echo	     88"""""""88 ,d8P""""          88""""Yb,   
echo	     88       88 d8"               88     "8b  
echo	     88       88 Y8,               88      `8i 
echo	     88       Y8,`Yba,,_____,      88       Yb,
echo	     88       `Y8  `"Y8888888      88        Y8
timeout /t 5 > nul
cls
echo I
timeout /t 1 > nul 
echo found
timeout /t 1 > nul
echo	 ,ggg,        gg    ,ggggggg,  ,ggggggggggg,   
echo	dP""Y8b       88  ,dP""""""Y8bdP"""88""""""Y8, 
echo	Yb, `88       88  d8'    a  Y8Yb,  88      `8b 
echo	 `"  88       88  88     "Y8P' `"  88      ,8P 
echo	     88aaaaaaa88  `8baaaa          88aaaad8P"  
echo	     88"""""""88 ,d8P""""          88""""Yb,   
echo	     88       88 d8"               88     "8b  
echo	     88       88 Y8,               88      `8i 
echo	     88       Y8,`Yba,,_____,      88       Yb,
echo	     88       `Y8  `"Y8888888      88        Y8
timeout /t 120 > nul